const NEWS = [
  // category: 'event' | 'media' | 'release' | 'other'
  {
    id: '',
    date: '',
    category: 'event',
    title: '',
    titleEn: '',
    body: '',
    bodyEn: '',
    url: '',
    image: '',
  },
  {
    id: '',
    date: '',
    category: 'media',
    title: '',
    titleEn: '',
    body: '',
    bodyEn: '',
    url: '',
    image: '',
  },
  {
    id: '',
    date: '',
    category: 'release',
    title: '',
    titleEn: '',
    body: '',
    bodyEn: '',
    url: '',
    image: '',
  },
];
