const NEWS = [
  // category: 'event' | 'media' | 'release' | 'other'
  {
    id: 'news-test-event-1',
    date: '2026.05.10',
    category: 'event',
    title: '[TEST] 渋谷 WOMB にてライブセット出演',
    titleEn: '[TEST] Live Set Performance at Shibuya WOMB',
    body: '2026年5月10日（土）、渋谷 WOMB にて開催される電子音楽イベント「SIGNAL TOKYO vol.12」にライブセットで出演いたします。Dubstep〜Drum\'n\'Bassを軸にした45分間のオリジナルセットを披露予定です。',
    bodyEn: 'Performing a 45-minute original live set at "SIGNAL TOKYO vol.12," an electronic music event held at Shibuya WOMB on May 10, 2026. The set will be centered around Dubstep and Drum\'n\'Bass.',
    url: '',
    image: '',
  },
  {
    id: 'news-test-media-1',
    date: '2026.04.22',
    category: 'media',
    title: '[TEST] DTMマガジン5月号にインタビュー掲載',
    titleEn: '[TEST] Interview Featured in DTM Magazine May Issue',
    body: '月刊誌「DTMマガジン」2026年5月号の特集「次世代サウンドクリエイター10人」にインタビューが掲載されました。制作環境・ワークフロー・広告音楽の現場について詳しくお話しています。全国書店・Amazonにて発売中です。',
    bodyEn: 'An interview with me is featured in the May 2026 issue of DTM Magazine, in their "10 Next-Generation Sound Creators" special. I discuss my production setup, workflow, and the world of advertising music. Available at bookstores nationwide and on Amazon.',
    url: '',
    image: '',
  },
  {
    id: 'news-test-release-1',
    date: '2026.04.05',
    category: 'release',
    title: '[TEST] 新曲「Afterimage」リリース',
    titleEn: '[TEST] New Track "Afterimage" Released',
    body: 'Self Worksとして制作した新曲「Afterimage」を各種ストリーミングサービスにてリリースしました。映像との融合をテーマに、ポストダブステップとオーケストラルサウンドを組み合わせた楽曲です。Spotify・Apple Music・YouTube Musicにてお聴きいただけます。',
    bodyEn: 'My new self-produced track "Afterimage" is now available on all major streaming platforms. The track combines post-dubstep and orchestral sound, themed around the fusion of music and visuals. Listen on Spotify, Apple Music, and YouTube Music.',
    url: '',
    image: '',
  },
  {
    id: 'news-test-event-2',
    date: '2026.03.18',
    category: 'event',
    title: '[TEST] 九州大学 芸術工学部にてゲスト講義',
    titleEn: '[TEST] Guest Lecture at Kyushu University Faculty of Design',
    body: '母校・九州大学芸術工学部音響設計学科にてゲスト講義を行いました。「フリーランスサウンドクリエイターの実際」と題し、在学中の学生に向けて、広告音楽制作の実務・営業・キャリア形成について約90分お話しさせていただきました。',
    bodyEn: 'I gave a guest lecture at my alma mater, Kyushu University\'s Department of Acoustic Design. Under the title "The Reality of Freelance Sound Creation," I spoke for around 90 minutes to current students about the practical side of advertising music production, client acquisition, and building a career.',
    url: '',
    image: '',
  },
  {
    id: 'news-test-media-2',
    date: '2026.02.14',
    category: 'media',
    title: '[TEST] Web メディア「Sound & Vision」にて作品紹介',
    titleEn: '[TEST] Works Featured on Web Media "Sound & Vision"',
    body: '音楽と映像の融合をテーマにしたWebメディア「Sound & Vision」にて、サントリー BOSS CM およびポケモンGO Fest 2025の楽曲制作について取り上げていただきました。制作の裏側やクライアントとのやり取りについて詳しく語っています。',
    bodyEn: 'Web media outlet "Sound & Vision," focused on the intersection of music and visuals, featured a piece on my work for the Suntory BOSS CM and the Pokémon GO Fest 2025 web commercial. The article goes in depth on the production process and collaboration with clients.',
    url: '',
    image: '',
  },
  {
    id: 'news-test-other-1',
    date: '2026.01.30',
    category: 'other',
    title: '[TEST] 株式会社インビジ 公式サイトにてインタビュー公開',
    titleEn: '[TEST] Interview Published on Invisi Inc. Official Website',
    body: '所属する株式会社インビジの公式サイトにて、社員インタビューが公開されました。入社の経緯、音楽制作における会社のサポート、今後の展望などについて語っています。インビジ公式サイトよりご覧いただけます。',
    bodyEn: 'An employee interview with me has been published on the official website of Invisi Inc., the company I belong to. I talk about how I joined the company, the support I receive for music production, and my future goals. Available on the Invisi official website.',
    url: '',
    image: '',
  },
];
